;**********************************
;  Program : ARP
;            ARray Polar
;            By Jong-Suk Yi
;            1995. 2. 27,5/24, 7/20
;*********************************
(defun c:ARP(/
        ent     elist   cen     ra      sp      ep
        sang    eang    seang   angsgn  cl      delta   num
        rmd     rmang   rmdst   nang    nnum    arent
)

  (defun SETERR(s)
    (if (/= s "Function cancelled")
        (princ (strcat "\nError: " s))
    ); of If
    (setq *error* oer seterr nil)
    (princ)
  ); of SETERR
  (setq oer *error* *error* seterr)

  (push-env)

  (setq ent (entsel "\nSelect Arc or Circle: "))    ;顶贰a 选迦

  (setq elist (entget (car ent)))
  (setq cen (cdr (assoc 10 elist)))                 ;惫廖a
  (setq ra (cdr (assoc 40 elist)))                  ;ew

  (setq sp (getpoint "\nPick start point: "))       ;array 「b格
  (setq ep (getpoint "\nPick End point: "))         ;array {格

  (setq sang (angle cen sp))                        ;「b格 搁b
  (princ "\nstart angle") (princ (rtod sang))

  (setq eang (angle cen ep))                        ;{格 搁b
  (princ "\nend angle") (princ (rtod eang))

  (setq seang (- eang sang))                        ;「b格 {格 a
  (princ "\nseangle: ") (princ (rtod seang))

  (setq angsgn (/ seang (abs seang)))               ;「b格 {格 a 选
  (princ "\nSign of angle: ") (princ angsgn)

  (setq cl (/ (* 2 pi ra seang) (* 2 pi)))          ;选 ┓
  (princ "\nCurve length: ")
  (princ (rtos cl 2 (getvar "LUPREC")))             ;选 ┓ a

  (setq delta (getreal "\nEnter Delta: "))          ;delta L 烦b
  (setq num (abs (fix (/ cl delta))))               ;array  q
  (princ "\nNumber: ") (princ num)

  (setq rmd (rem cl delta))                         ;a峄
  (princ "\nRemand: ") (princ rmd)

  ;(setq rmdst (* rmd delta))
  (setq rmdst rmd)
  (princ "\nRemaind dist: ") (princ rmdst)

  (setq rmang (* (/ (* 360.0 rmdst) (* 2.0 pi ra)) angsgn))  ;a峄 b

  (princ "\nradius: ") (princ ra)
  (princ "\nremaind ang: ") (princ rmang)
  (setq nang (- (rtod seang) (* rmang angsgn)))
  (princ "\nStart angle: ") (princ (rtod sang))
  (princ "\nEnd angle: ") (princ (rtod eang))
  (princ "\nNew angle: ") (princ nang)

  (setq arent (ssget))           ;arrayi entity迦

  (setq nnum (abs (+ num 1)))                                ;array

  (command "array" arent "" "p" cen nnum nang "y")           ;arrayww 

  (pop-env)
  (setq *error* oer seterr nil)
  (princ)

) ;;; End of program

